module.exports = {
	main: function(bot, message) {
		var pt1 = "What the fuck did you just fucking say about me, you little freshman? I’ll have you know I was the top driver of my team, ";
		var pt2 = ", and I’ve been involved in numerous world championships, and I have over 300 confirmed high goals. I am trained in boulder warfare and I was the top manipulator in FRC Stronghold in the entire US. You are nothing to me but just another castle lined with retro-reflective tape. I will wipe you the fuck out with precision the likes of which has never been seen before on this Earth, mark my fucking words. You think you can get away with saying that shit to me over the Internet? Think again, fucker. As we speak I am contacting my secret network of scouts across the stands and your robot IP is being traced right now so you better prepare for the DDOS, fagg-t. The mango storm that wipes out the pathetic little thing you call your robot and any tiny chance you ever had at winning. You’re fucking dead, kid. I can be anywhere, anytime, and I can dunk boulders over you in over seven hundred ways, and that’s just with my bare hands. Not only am I extensively trained in unarmed mango smoothie making, but I have access to the entire arsenal of the FRC machine shop and I will use it to its full extent to wipe your entire team out of FRC, you little sh-t. If only you could have known what unholy retribution your little “clever” comment was about to bring down upon you and your team, maybe you would have held your fucking tongue. But you couldn’t, you didn’t, and now you’re paying the price, you goddamn idiot. I will shit crappy code all over you and you will drown in it. You’re fucking dead, kiddo.";
		var team = message.content;
		
		message.channel.sendMessage(pt1 + team + pt2);
	}
};
